/******************************************************************************
Finite State Machine
Project: fsm.dot
Description: control logic

Generated by gv2fsm, see https://github.com/pbosetti/gv2fsm
gv2fsm version 1.2.1
Generation date: 2026-06-16 16:04:26
Generated from: fsm.dot
The finite state machine has:
  7 states
  7 distinct transition functions
  17 transitions with an associated function

******************************************************************************/
#ifndef FSM_HPP
#define FSM_HPP
#include <functional>
#include <iostream>
#include <map>
#include <string>
#include <tuple>


using namespace std::string_literals;
namespace FSM {

// List of states
typedef enum {
  STATE_INIT,
  STATE_IDLE,
  STATE_PATH_FOLLOWING_IDLE,
  STATE_IMPEDANCE_CONTROL_IDLE,
  STATE_PATH_FOLLOWING_ACTIVE,
  STATE_IMPEDANCE_CONTROL_ACTIVE,
  STATE_SHUTDOWN,
  NUM_STATES,
  NO_CHANGE,
  UNIMPLEMENTED
} state_t;

// State human-readable names
std::map<state_t, char const *> state_names = {
  { STATE_INIT, "INIT" },
  { STATE_IDLE, "IDLE" },
  { STATE_PATH_FOLLOWING_IDLE, "PATH_FOLLOWING_IDLE" },
  { STATE_IMPEDANCE_CONTROL_IDLE, "IMPEDANCE_CONTROL_IDLE" },
  { STATE_PATH_FOLLOWING_ACTIVE, "PATH_FOLLOWING_ACTIVE" },
  { STATE_IMPEDANCE_CONTROL_ACTIVE, "IMPEDANCE_CONTROL_ACTIVE" },
  { STATE_SHUTDOWN, "SHUTDOWN" },
  { NUM_STATES, "NUM_STATES" },
  { NO_CHANGE, "NO_CHANGE" },
  { UNIMPLEMENTED, "UNIMPLEMENTED" }
};

// Custom state functions:
template<class T> 
state_t do_init(T &data);
template<class T> 
state_t do_idle(T &data);
template<class T> 
state_t do_path_following_idle(T &data);
template<class T> 
state_t do_impedance_control_idle(T &data);
template<class T> 
state_t do_path_following_active(T &data);
template<class T> 
state_t do_impedance_control_active(T &data);
template<class T> 
state_t do_shutdown(T &data);

// Custom transition functions:
template<class T>
void transition_to_active_mode(T &data);
template<class T>
void transition_to_inactive_mode(T &data);
template<class T>
void start_events(T &data);
template<class T>
void transition_to_idle(T &data);
template<class T>
void end_events(T &data);
template<class T>
void check_emergency_button(T &data);
template<class T>
void check_detections(T &data);

// Finite State Machine class
template <typename DATA_T> 
class FiniteStateMachine {

// Function templates
using state_fun = std::function<state_t(DATA_T &data)>;
using transition_fun = std::function<void(DATA_T &data)>;
using operation_fun = std::function<void(DATA_T &data)>;

private:
  std::pair<state_t, state_t> _state{ STATE_INIT, STATE_INIT };
  std::map<state_t, state_fun> _states;
  std::map<state_t, std::map<state_t, transition_fun>> _transitions;
  std::function<void()> _timing_func;
  DATA_T *_data;

public:

  FiniteStateMachine(DATA_T *data) : _data(data) {
    install_functions();
  }
  ~FiniteStateMachine(){};

  void set_timing_function(std::function<void()> timing_func) {
    _timing_func = timing_func;
  }

  void add_state(state_t name, state_fun func) { _states[name] = func; }

  void add_transition(state_t from, state_t to, transition_fun func) {
    _transitions[from][to] = func;
  }

  inline state_t state() { return _state.second; }
  inline std::string state_name() { return std::string(state_names[_state.second]); }
  inline state_t prev_state() { return _state.first; }

  state_t operator()(state_t state) {
    if (_states.find(state) == _states.end()) {
      throw std::runtime_error("State not found: "s + state_names[state]);
    }
    state_t next = _states[state](*_data);
    if (next == NO_CHANGE) {
      next = state;
    }
    return next;
  }

  void operator()(state_t from, state_t to) {
    if (_transitions.find(from) != _transitions.end()) {
      if (_transitions[from].find(to) != _transitions[from].end()) {
        _transitions[from][to](*_data);
      }
    }
  }


  // Setup initial state links
  void setup(state_t state) {
    _state.first = state;
    _state.second = state;
  }

  // Evaluate the current state and update the next state
  // to be used when main loop is customized (i.e., not using FSM::run())
  state_t eval_state() {
      _state.first = _state.second;
      _state.second = (*this)(_state.second);
      (*this)(_state.first, _state.second);
      return _state.second;
  }

  // Run the FSM from a given state
  void run(state_t state, operation_fun operation = nullptr) {
    setup(state);
    do {
      if (operation) {
        operation(*_data);
      }
      eval_state();
      if (_timing_func) {
        _timing_func();
      }
    } while (_state.second != STATE_SHUTDOWN);
    // Call the exit state once more:
    (*this)(STATE_SHUTDOWN);
  }

  // Run the FSM from the initial state
  void run(operation_fun operation = nullptr) { run(STATE_INIT, operation); }

  // install state and transition functions
  void install_functions() {

    // State functions
    add_state(FSM::STATE_INIT, [](DATA_T &data) -> FSM::state_t {
      FSM::state_t next_state = do_init(data);
    
      switch (next_state) {
      case FSM::UNIMPLEMENTED:
        throw std::runtime_error("State function not fully implemented: "s + "INIT");
        break;
      case FSM::STATE_IDLE:
        break;
      default:
        throw std::runtime_error("Invalid state transition from INIT to "s + state_names[next_state]);
      }
      return next_state;
    });

    add_state(FSM::STATE_IDLE, [](DATA_T &data) -> FSM::state_t {
      FSM::state_t next_state = do_idle(data);
    
      switch (next_state) {
      case FSM::UNIMPLEMENTED:
        throw std::runtime_error("State function not fully implemented: "s + "IDLE");
        break;
      case FSM::NO_CHANGE:
      case FSM::STATE_PATH_FOLLOWING_IDLE:
      case FSM::STATE_IMPEDANCE_CONTROL_IDLE:
      case FSM::STATE_SHUTDOWN:
      case FSM::STATE_IDLE:
        break;
      default:
        throw std::runtime_error("Invalid state transition from IDLE to "s + state_names[next_state]);
      }
      return next_state;
    });

    add_state(FSM::STATE_PATH_FOLLOWING_IDLE, [](DATA_T &data) -> FSM::state_t {
      FSM::state_t next_state = do_path_following_idle(data);
    
      switch (next_state) {
      case FSM::UNIMPLEMENTED:
        throw std::runtime_error("State function not fully implemented: "s + "PATH_FOLLOWING_IDLE");
        break;
      case FSM::NO_CHANGE:
      case FSM::STATE_PATH_FOLLOWING_ACTIVE:
      case FSM::STATE_IDLE:
      case FSM::STATE_PATH_FOLLOWING_IDLE:
        break;
      default:
        throw std::runtime_error("Invalid state transition from PATH_FOLLOWING_IDLE to "s + state_names[next_state]);
      }
      return next_state;
    });

    add_state(FSM::STATE_IMPEDANCE_CONTROL_IDLE, [](DATA_T &data) -> FSM::state_t {
      FSM::state_t next_state = do_impedance_control_idle(data);
    
      switch (next_state) {
      case FSM::UNIMPLEMENTED:
        throw std::runtime_error("State function not fully implemented: "s + "IMPEDANCE_CONTROL_IDLE");
        break;
      case FSM::NO_CHANGE:
      case FSM::STATE_IMPEDANCE_CONTROL_ACTIVE:
      case FSM::STATE_IDLE:
      case FSM::STATE_IMPEDANCE_CONTROL_IDLE:
        break;
      default:
        throw std::runtime_error("Invalid state transition from IMPEDANCE_CONTROL_IDLE to "s + state_names[next_state]);
      }
      return next_state;
    });

    add_state(FSM::STATE_PATH_FOLLOWING_ACTIVE, [](DATA_T &data) -> FSM::state_t {
      FSM::state_t next_state = do_path_following_active(data);
    
      switch (next_state) {
      case FSM::UNIMPLEMENTED:
        throw std::runtime_error("State function not fully implemented: "s + "PATH_FOLLOWING_ACTIVE");
        break;
      case FSM::NO_CHANGE:
      case FSM::STATE_PATH_FOLLOWING_IDLE:
      case FSM::STATE_IDLE:
      case FSM::STATE_PATH_FOLLOWING_ACTIVE:
        break;
      default:
        throw std::runtime_error("Invalid state transition from PATH_FOLLOWING_ACTIVE to "s + state_names[next_state]);
      }
      return next_state;
    });

    add_state(FSM::STATE_IMPEDANCE_CONTROL_ACTIVE, [](DATA_T &data) -> FSM::state_t {
      FSM::state_t next_state = do_impedance_control_active(data);
    
      switch (next_state) {
      case FSM::UNIMPLEMENTED:
        throw std::runtime_error("State function not fully implemented: "s + "IMPEDANCE_CONTROL_ACTIVE");
        break;
      case FSM::NO_CHANGE:
      case FSM::STATE_IMPEDANCE_CONTROL_IDLE:
      case FSM::STATE_IDLE:
      case FSM::STATE_IMPEDANCE_CONTROL_ACTIVE:
        break;
      default:
        throw std::runtime_error("Invalid state transition from IMPEDANCE_CONTROL_ACTIVE to "s + state_names[next_state]);
      }
      return next_state;
    });

    add_state(FSM::STATE_SHUTDOWN, [](DATA_T &data) -> FSM::state_t {
      FSM::state_t next_state = do_shutdown(data);
    
      switch (next_state) {
      case FSM::UNIMPLEMENTED:
        throw std::runtime_error("State function not fully implemented: "s + "SHUTDOWN");
        break;
      case FSM::NO_CHANGE:
        break;
      default:
        throw std::runtime_error("Invalid state transition from SHUTDOWN to "s + state_names[next_state]);
      }
      return next_state;
    });


    // Transition functions
    add_transition(STATE_PATH_FOLLOWING_IDLE, STATE_PATH_FOLLOWING_ACTIVE, [](DATA_T &data) {
      transition_to_active_mode(data);
    });

    add_transition(STATE_IMPEDANCE_CONTROL_IDLE, STATE_IMPEDANCE_CONTROL_ACTIVE, [](DATA_T &data) {
      transition_to_active_mode(data);
    });

    add_transition(STATE_IMPEDANCE_CONTROL_ACTIVE, STATE_IMPEDANCE_CONTROL_IDLE, [](DATA_T &data) {
      transition_to_inactive_mode(data);
    });

    add_transition(STATE_PATH_FOLLOWING_ACTIVE, STATE_PATH_FOLLOWING_IDLE, [](DATA_T &data) {
      transition_to_inactive_mode(data);
    });

    add_transition(STATE_IDLE, STATE_PATH_FOLLOWING_IDLE, [](DATA_T &data) {
      transition_to_inactive_mode(data);
    });

    add_transition(STATE_IDLE, STATE_IMPEDANCE_CONTROL_IDLE, [](DATA_T &data) {
      transition_to_inactive_mode(data);
    });

    add_transition(STATE_INIT, STATE_IDLE, [](DATA_T &data) {
      start_events(data);
    });

    add_transition(STATE_PATH_FOLLOWING_IDLE, STATE_IDLE, [](DATA_T &data) {
      transition_to_idle(data);
    });

    add_transition(STATE_IMPEDANCE_CONTROL_IDLE, STATE_IDLE, [](DATA_T &data) {
      transition_to_idle(data);
    });

    add_transition(STATE_PATH_FOLLOWING_ACTIVE, STATE_IDLE, [](DATA_T &data) {
      transition_to_idle(data);
    });

    add_transition(STATE_IMPEDANCE_CONTROL_ACTIVE, STATE_IDLE, [](DATA_T &data) {
      transition_to_idle(data);
    });

    add_transition(STATE_IDLE, STATE_SHUTDOWN, [](DATA_T &data) {
      end_events(data);
    });

    add_transition(STATE_IDLE, STATE_IDLE, [](DATA_T &data) {
      check_emergency_button(data);
    });

    add_transition(STATE_PATH_FOLLOWING_IDLE, STATE_PATH_FOLLOWING_IDLE, [](DATA_T &data) {
      check_emergency_button(data);
    });

    add_transition(STATE_IMPEDANCE_CONTROL_IDLE, STATE_IMPEDANCE_CONTROL_IDLE, [](DATA_T &data) {
      check_emergency_button(data);
    });

    add_transition(STATE_PATH_FOLLOWING_ACTIVE, STATE_PATH_FOLLOWING_ACTIVE, [](DATA_T &data) {
      check_detections(data);
    });

    add_transition(STATE_IMPEDANCE_CONTROL_ACTIVE, STATE_IMPEDANCE_CONTROL_ACTIVE, [](DATA_T &data) {
      check_detections(data);
    });

  }

}; // class FiniteStateMachine

}; // namespace FSM

#include "fsm_impl.hpp"

#endif // FSM_HPP
