/******************************************************************************
Finite State Machine
Project: fsm.dot
Description: control logic

Generated by gv2fsm, see https://github.com/pbosetti/gv2fsm
gv2fsm version 1.2.1
Generation date: 2026-06-16 16:04:26
Generated from: fsm.dot
The finite state machine has:
  7 states
  7 distinct transition functions
  17 transitions with an associated function

******************************************************************************/
    
using namespace std;
    
// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!


namespace FSM {

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                             

// Function to be executed in state STATE_INIT
// valid return states: STATE_IDLE
template<class T> 
state_t do_init(T &data) {
  state_t next_state = FSM::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_IDLE
// valid return states: NO_CHANGE, STATE_PATH_FOLLOWING_IDLE, STATE_IMPEDANCE_CONTROL_IDLE, STATE_SHUTDOWN, STATE_IDLE
template<class T> 
state_t do_idle(T &data) {
  state_t next_state = FSM::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_PATH_FOLLOWING_IDLE
// valid return states: NO_CHANGE, STATE_PATH_FOLLOWING_ACTIVE, STATE_IDLE, STATE_PATH_FOLLOWING_IDLE
template<class T> 
state_t do_path_following_idle(T &data) {
  state_t next_state = FSM::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_IMPEDANCE_CONTROL_IDLE
// valid return states: NO_CHANGE, STATE_IMPEDANCE_CONTROL_ACTIVE, STATE_IDLE, STATE_IMPEDANCE_CONTROL_IDLE
template<class T> 
state_t do_impedance_control_idle(T &data) {
  state_t next_state = FSM::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_PATH_FOLLOWING_ACTIVE
// valid return states: NO_CHANGE, STATE_PATH_FOLLOWING_IDLE, STATE_IDLE, STATE_PATH_FOLLOWING_ACTIVE
template<class T> 
state_t do_path_following_active(T &data) {
  state_t next_state = FSM::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_IMPEDANCE_CONTROL_ACTIVE
// valid return states: NO_CHANGE, STATE_IMPEDANCE_CONTROL_IDLE, STATE_IDLE, STATE_IMPEDANCE_CONTROL_ACTIVE
template<class T> 
state_t do_impedance_control_active(T &data) {
  state_t next_state = FSM::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_SHUTDOWN
// valid return states: NO_CHANGE
template<class T> 
state_t do_shutdown(T &data) {
  state_t next_state = FSM::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}


/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                              

// This function is called in 2 transitions:
// 1. from path_following_idle to path_following_active
// 2. from impedance_control_idle to impedance_control_active
template<class T>
void transition_to_active_mode(T &data) {
  /* Your Code Here */
}

// This function is called in 4 transitions:
// 1. from impedance_control_active to impedance_control_idle
// 2. from path_following_active to path_following_idle
// 3. from idle to path_following_idle
// 4. from idle to impedance_control_idle
template<class T>
void transition_to_inactive_mode(T &data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from init to idle
template<class T>
void start_events(T &data) {
  /* Your Code Here */
}

// This function is called in 4 transitions:
// 1. from path_following_idle to idle
// 2. from impedance_control_idle to idle
// 3. from path_following_active to idle
// 4. from impedance_control_active to idle
template<class T>
void transition_to_idle(T &data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from idle to shutdown
template<class T>
void end_events(T &data) {
  /* Your Code Here */
}

// This function is called in 3 transitions:
// 1. from idle to idle
// 2. from path_following_idle to path_following_idle
// 3. from impedance_control_idle to impedance_control_idle
template<class T>
void check_emergency_button(T &data) {
  /* Your Code Here */
}

// This function is called in 2 transitions:
// 1. from path_following_active to path_following_active
// 2. from impedance_control_active to impedance_control_active
template<class T>
void check_detections(T &data) {
  /* Your Code Here */
}


}; // namespace FSM


// Example usage:
#ifdef TEST_MAIN
#include <unistd.h>
#include <thread>

struct Data {
  int count;
};

int main() {
  Data data = {1};
  auto fsm = FSM::FiniteStateMachine(&data);
  fsm.set_timing_function([]() {
    std::this_thread::sleep_for(std::chrono::seconds(1));
  });
  fsm.run([&](Data &s) {
    std::cout << "State: " << fsm.state() << " data: " << s.count << std::endl;
  });
  return 0;
}

#endif // TEST_MAIN
